[[GR]]
arch = "aarch64"
git-tree-sha1 = "2f69ba32dc9ae0c515d855f5a3d6afced2355693"
os = "macos"

    [[GR.download]]
    sha256 = "f011df6d240887021932af3a0335118dcc1013fa1fb0bd1201c0b7073643cf4c"
    url = "https://github.com/barche/GR_jll.jl/releases/download/GR-v0.72.8+1/GR.v0.72.8.aarch64-apple-darwin.tar.gz"
[[GR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec3fbc66b010af724efed0546d1696eca0fbda3f"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "a7a8754483240b4f46c47b93e0ae66aacf7ff93965f2fa7c177fd498a49d5297"
    url = "https://github.com/barche/GR_jll.jl/releases/download/GR-v0.72.8+1/GR.v0.72.8.aarch64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e5f7d7088140cc306148eddfc4ec887450965e9"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "417c11f53185bd6e91ba567a49d4bf5097c2e89014a444cf33482d5d938dce2e"
    url = "https://github.com/barche/GR_jll.jl/releases/download/GR-v0.72.8+1/GR.v0.72.8.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
git-tree-sha1 = "055972a490aae0a70929bce6dcc72d2282dbba58"
os = "macos"

    [[GR.download]]
    sha256 = "1b61c1a3023d9f2f7da70e5bfc83d84dec61ee7ce71c18da2510a370484a757a"
    url = "https://github.com/barche/GR_jll.jl/releases/download/GR-v0.72.8+1/GR.v0.72.8.x86_64-apple-darwin.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59192969c4fa5e650c2af72f32dac7d7c805f796"
libc = "glibc"
os = "linux"

    [[GR.download]]
    sha256 = "41f44de0d2c9ac5b6d45b5139c0f42ef0639fe13f6032fa8ac8b5f6f85aa36f9"
    url = "https://github.com/barche/GR_jll.jl/releases/download/GR-v0.72.8+1/GR.v0.72.8.x86_64-linux-gnu-cxx11.tar.gz"
[[GR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9ad61feb5a2456d8b789a23afecf335b0c32f39"
os = "windows"

    [[GR.download]]
    sha256 = "911613f6db7174a87d1cd203d7578334bf622c80f7aa539ffd4ad2d4ad96e0eb"
    url = "https://github.com/barche/GR_jll.jl/releases/download/GR-v0.72.8+1/GR.v0.72.8.x86_64-w64-mingw32-cxx11.tar.gz"
